default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: error_note_sample_development

test:
  <<: *default
  database: error_note_sample_test

production:
  <<: *default
  database: error_note
  host: <%= ENV['ERROR_NOTE_DATABASE_HOST'] %>
  username: <%= ENV['ERROR_NOTE_DATABASE_USERNAME'] %>
  password: <%= ENV['ERROR_NOTE_DATABASE_PASSWORD'] %>
