default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: error_note_sample_development

test:
  <<: *default
  database: error_note_sample_test

production:
  <<: *default
  database: error_note_sample_production
  username: error_note_sample
  password: <%= ENV['ERROR_NOTE_SAMPLE_DATABASE_PASSWORD'] %>
